package quizapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author calde
 */
public class QuizAppGUI extends javax.swing.JPanel {
    /**
     * Creates new form QuizAppGUI
     */
     public QuizAppGUI() {
        initComponents();
        EventListener listener = new EventListener();
        EventListener listenera = new EventListener();
        EventListener listenerb = new EventListener();
        createQuestionButton.addActionListener(listener);
        nextQuestionButton.addActionListener(listenera);
        showAnswerButton.addActionListener(listenera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerQuestionsTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        createQuestionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        questionCreation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        answerCreation = new javax.swing.JTextField();
        createAnswerButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        showAnswerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionShowcase = new javax.swing.JTextArea();
        nextQuestionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerShowcase = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        answerQuestionsTab.setPreferredSize(new java.awt.Dimension(800, 600));

        createQuestionButton.setText("Create Question");

        jLabel1.setText("Question");

        jLabel2.setText("Answer");

        answerCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCreationActionPerformed(evt);
            }
        });

        createAnswerButton.setText("Create Answer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAnswerButton)
                    .addComponent(createQuestionButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(questionCreation, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                        .addComponent(answerCreation)
                        .addComponent(jLabel2)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createQuestionButton)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAnswerButton)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        answerQuestionsTab.addTab("Create Questions", jPanel1);

        showAnswerButton.setText("Show Answer");
        showAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAnswerButtonActionPerformed(evt);
            }
        });

        questionShowcase.setColumns(20);
        questionShowcase.setRows(5);
        jScrollPane2.setViewportView(questionShowcase);

        nextQuestionButton.setText("Next Question");

        answerShowcase.setColumns(20);
        answerShowcase.setRows(5);
        jScrollPane1.setViewportView(answerShowcase);

        jLabel3.setText("Question");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(showAnswerButton, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(nextQuestionButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(showAnswerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(nextQuestionButton)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        answerQuestionsTab.addTab("Answer Questions", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerQuestionsTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerQuestionsTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void answerCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCreationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerCreationActionPerformed

    private void showAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAnswerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAnswerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerCreation;
    private javax.swing.JTabbedPane answerQuestionsTab;
    private javax.swing.JTextArea answerShowcase;
    private javax.swing.JButton createAnswerButton;
    private javax.swing.JButton createQuestionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextQuestionButton;
    private javax.swing.JTextField questionCreation;
    private javax.swing.JTextArea questionShowcase;
    private javax.swing.JButton showAnswerButton;
    // End of variables declaration//GEN-END:variables
//My variables
  public  Boolean checkStringLength(String inputString, Integer minLength, Integer maxLength)
    {
        int stringLength = inputString.length();
        
        if (stringLength >= minLength && stringLength <= maxLength){
            System.out.println("pass");
            return true;           
        }
        else{
            System.out.println("fail");
            return false;
        } 
        } 
    /**
     * inner event listener class - private.  This class handles GUI Events
     * ===Save Question Button===
     *  When the save question button is clicked:
     *  -the question string is passed to checkStringLength with a min length of 3 and a max length of 60.  If the string fails this test, an error box
     *      is shown and the question must be re-entered.
     *  -a new instance of Question is created within the instance of QuizApp
     *  -the instance of Question is added to the arrayList of Questions in QuizApp
     *  - the eventName is added to the select question combo boxes on the results tab and the add results tab.
     */
     private class EventListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
           
        if(e.getSource() == createQuestionButton){
        System.out.println("createQuestionButton triggered");
        
        String testQuestion = questionCreation.getText();
        Boolean test = checkStringLength(testQuestion,3,60);
        if (test == false){
           System.out.println("false part");
           JOptionPane.showMessageDialog(new JFrame(),
           "Error - question needs to be between 3 and 60 characters in length",
           "Create Question Error",
           JOptionPane.ERROR_MESSAGE);
           questionCreation.setText("");}
        else {
        String question = questionCreation.toString();
        QuizApp.createNewQuestion(question);//Create a new question in the QuizApp object.
        System.out.println("success");
        questionCreation.setText("");
        }
        }
        if(e.getSource() == createAnswerButton){
        System.out.println("createAnswerButton triggered");
        String testAnswer = answerCreation.getText();
        Boolean test = checkStringLength(testAnswer,1,60);
        if (test == false){
           System.out.println("false part");
           JOptionPane.showMessageDialog(new JFrame(),
           "Error - answer needs to be between 1 and 60 characters in length",
           "Create Answer Error",
           JOptionPane.ERROR_MESSAGE);
           answerCreation.setText("");}
        else{
        String answer = answerCreation.toString();
        QuizApp.createNewAnswer(answer);//Create a new answer in the QuizApp object.
        System.out.println("success");
        answerCreation.setText("");
}
        }
          if(e.getSource() == answerQuestionsTab){
        System.out.println("answerQuestionsTab opened");
        String questionf = QuizApp.getQuestionF(question);
        questionShowcase.setText(questionf);
        }

        }
        }
}